---
title: "R Notebook"
output: html_notebook
---

```{r}
library(nycflights13)

View(flights)
View(airports)
View(planes)
View(airlines)
View(weather)

library(tidyverse)
library(gapminder)

```

inner-join

```{r}
flights %>%
  inner_join(planes,by=c("tailnum"="tailnum"))

flights %>%
  inner_join(airlines,by=c("carrier"="carrier"))

flights %>%
  inner_join(airports,by=c("origin"="faa"))

flights %>%
  inner_join(airports,by=c("dest"="faa"))

flights %>%
  inner_join(weather,by=c("year"="year","month"="month","day"="day","hour"="hour","origin"="origin"))




```
2. data manipulation
2.1
```{r}

flights %>%
  count(year,month,day) %>%
  filter(n>1000) %>%
  arrange((n))



```

2.2
```{r}
flights %>%
  dplyr::select( year:day,hour,origin,dest,tailnum,carrier,arr_delay,dep_delay)

flights_selected<- flights  %>%
  dplyr::select( year:day,hour,origin,dest,tailnum,carrier,arr_delay,dep_delay)


```

2.3
```{r}
airlines %>%
  left_join(flights_selected,by=c("carrier"="carrier")) %>%
  dplyr::select(-origin,-dest) %>%
  mutate(tot_delay=arr_delay + dep_delay)



```
2.4
```{r}

precip_delay<-flights %>%
  inner_join(weather,by=c("year"="year","month"="month","day"="day","hour"="hour","origin"="origin"))%>%
  group_by(precip)%>%
  summarize(delay=mean(dep_delay,na.rm=TRUE))%>%
replace_na(list(delay = 0))



```

2.5
```{r}
ggplot(precip_delay, aes(x=precip, y=delay)) + geom_point()

```

2.6
```{r}

flights_airports<-flights %>%
  filter(year==2013)%>%
  filter(month==5)%>%
  filter(day==10)%>%
  group_by(dest)%>%
  summarise(delay=mean(arr_delay,na.rm=TRUE))%>%
  inner_join(airports,by=c("dest"="faa"))


```
2.7
```{r}
ggplot(flights_airports, aes(x=lon, y=lat, color=delay,size = delay )) + geom_point() 


```

2.8
```{r}

flights %>%
  inner_join(planes,by=c("tailnum"="tailnum"),suffix=c("_flights","_planes"))%>%
  transmute(tailnum,manufacturer,pi=(dep_delay + arr_delay) / air_time
)


```

